name: netlight_marketplace
version: '1.0'
profile: dbt_project

config-version: 2

model-paths: ["models"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"        # directory where compiled SQL and artifacts go
clean-targets: ["target", "dbt_modules"]

models:
  netlight_marketplace:
    +materialized: view
    staging:
      +schema: staging
    intermediate:
      +schema: intermediate
    marts:
      +schema: marts

seeds:
  +schema: raw
